---
logging:
  level: INFO
  loggers:
    assessment: DEBUG
database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: 123456
  url: 'jdbc:postgresql://db:5432/invoice'
swagger:
  resourcePackage: assessment.invoice.resources